name: Testing Terraform Modules examples

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: Set up dependencies
        working-directory: test/
        run: |
          go mod tidy

      - name: Testing modules
        working-directory: test/
        env:
          TF_VAR_REGION: ${{ secrets.OCI_CLI_REGION }}
          TF_VAR_USER: ${{ secrets.OCI_CLI_USER }}
          TF_VAR_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          TF_VAR_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          TF_VAR_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
        run: |
          go test
